stages:
  - code
  - pre-build
  - build

# variables:
#   DOCKER_HOST: tcp://docker:2375/
#   DOCKER_TLS_CERTDIR: ""
#   DOCKER_DRIVER: overlay2
#   SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 

# services:
#   - name: docker:dind
#     alias: docker

check-sensitive-information:
  stage: code
  image:
    name: "trufflesecurity/trufflehog:latest"
    entrypoint: [""]
  script:
    - trufflehog filesystem $CI_PROJECT_DIR --no-verification --fail --exclude-paths $CI_PROJECT_DIR/.truffle-scan/exclude-paths.txt
  allow_failure: false
  cache: {}

software-composition-analysis:
  stage: pre-build
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --exit-code 0 --scanners misconfig,vuln --output sca-report.txt $CI_PROJECT_DIR
    - trivy fs --exit-code 1 --scanners misconfig,vuln --severity HIGH,CRITICAL $CI_PROJECT_DIR
  artifacts:
    when: always
    paths:
      - sca-report.txt
  cache:
    paths:
      - .trivycache/
  allow_failure: false

sast-gosec:
  stage: pre-build
  image: golang:alpine
  before_script:
    - apk add --no-cache git jq
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
  script:
    - gosec -fmt=json -no-fail -out=sast-report.json $CI_PROJECT_DIR/...
    - |
      if jq '.Issues | map(select(.severity=="HIGH" or .severity=="CRITICAL")) | length > 0' sast-report.json | grep -q true; then
        echo "High or Critical vulnerabilities detected"
        exit 1
      fi
  artifacts:
    when: always
    paths:
      - sast-report.json
  allow_failure: false

sast-sonar:
  stage: pre-build
  image:
    name: sonarsource/sonar-scanner-cli:11
    entrypoint: [""]
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  script:
    - sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}"
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'

build-image-and-container-scanning:
    stage: build
    image: docker:latest
    before_script:
      - export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
      - echo $TRIVY_VERSION
      - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
      - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    script:
      - docker build -f $CI_PROJECT_DIR/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
      - ./trivy image --exit-code 0 --scanners vuln --output container-scanning-report.txt $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      - ./trivy image --exit-code 1 --scanners vuln --severity HIGH,CRITICAL $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA 
      - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    artifacts:
      when: always
      paths:
        - container-scanning-report.txt
    cache:
      paths:
        - .trivycache/
    allow_failure: false

