stages:
  - code
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    alias: docker
    # command: ["--tls=false", "--insecure-registry=https://registry.gitlab.mataelang.net", "--host=tcp://0.0.0.0:2375"]

check-sensitive-information:
  stage: code
  image: 
    name: "trufflesecurity/trufflehog:latest"
    entrypoint: [""]
  script:
    - trufflehog filesystem $CI_PROJECT_DIR --no-verification --fail --exclude-paths $CI_PROJECT_DIR/.truffle-scan/exclude-paths.txt
  allow_failure: false
  cache: {}

software-composition-analysis:
  stage: build
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --exit-code 0 --scanners misconfig,vuln --output sca-report.txt $CI_PROJECT_DIR
    - trivy fs --exit-code 1 --scanners misconfig,vuln --severity HIGH,CRITICAL $CI_PROJECT_DIR
  artifacts:
    when: always
    paths:
      - sca-report.txt
  cache:
    paths:
      - .trivycache/
  allow_failure: false

sast:
  stage: build
  image: golang:alpine
  needs:
    - job: software-composition-analysis
  before_script:
    - apk add --no-cache git jq
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
  script:
    - gosec -fmt=json -no-fail -out=sast-report.json $CI_PROJECT_DIR/...
    - |
      if jq '.Issues | map(select(.severity=="HIGH" or .severity=="CRITICAL")) | length > 0' sast-report.json | grep -q true; then
        echo "High or Critical vulnerabilities detected"
        exit 1
      fi
  artifacts:
    when: always
    paths:
      - sast-report.json
  allow_failure: false

build-image-and-container-scanning:
    stage: build
    needs:
      - job: sast
    before_script:
      - export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
      - echo $TRIVY_VERSION
      - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
      - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    script:
      - docker build -f $CI_PROJECT_DIR/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
      - ./trivy image --exit-code 0 --scanners vuln --output container-scanning-report.txt $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      - ./trivy image --exit-code 1 --scanners vuln --severity HIGH,CRITICAL $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA 
      - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    artifacts:
      when: always
      paths:
        - container-scanning-report.txt
    cache:
      paths:
        - .trivycache/  
    allow_failure: false

dast:
  stage: test
  before_script:
    - apk add --no-cache docker-compose
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker-compose -f .dast/docker-compose.yml up -d sensor-api broker schema-registry
    - sleep 30
    - docker-compose -f .dast/docker-compose.yml ps
    - docker-compose -f .dast/docker-compose.yml logs sensor-api
    - docker-compose -f .dast/docker-compose.yml logs broker
    - docker-compose -f .dast/docker-compose.yml logs schema-registry
  script:
    - docker-compose -f .dast/docker-compose.yml run --rm grpc-dast

post-dast-remove-image:
  stage: test
  needs: 
    - job: dast
  when: on_failure
  before_script:
    - apk add curl
    - curl --fail-with-body --location "https://github.com/regclient/regclient/releases/download/v0.8.3/regctl-linux-amd64" > /usr/bin/regctl
    - chmod 755 /usr/bin/regctl
    - regctl registry login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - regctl tag rm $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - exit 1

post-dast-retag-image:
  stage: test
  needs: 
    - job: dast
  when: on_success  
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

deploy-to-prod:
  stage: deploy
  when: manual
  before_script: 
    - apk add --no-cache openssh-client rsync coreutils
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H $SSH_ADDRESS >> ~/.ssh/known_hosts
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_ADDRESS echo "SSH OKE"
    - export SHA_REPO_SENSOR_COMPOSE=$(sha256sum $CI_PROJECT_DIR/.deploy/sensor_snort/compose.yml | awk '{print $1}')
    - export SHA_REPO_SENSOR_ENV=$(sha256sum $CI_PROJECT_DIR/.deploy/sensor_snort/.env.example | awk '{print $1}')
    - export SHA_REPO_DC_COMPOSE=$(sha256sum $CI_PROJECT_DIR/.deploy/defense_center/compose.yml | awk '{print $1}')
    - export SHA_REPO_DC_ENV=$(sha256sum $CI_PROJECT_DIR/.deploy/defense_center/.env.example | awk '{print $1}')
    - export SHA_REMOTE_SENSOR_COMPOSE=$(ssh $SSH_USER@$SSH_ADDRESS sha256sum $DEPLOY_PATH/sensor_snort/compose.yml || echo "NONE")
    - export SHA_REMOTE_SENSOR_ENV=$(ssh $SSH_USER@$SSH_ADDRESS sha256sum $DEPLOY_PATH/sensor_snort/.env || echo "NONE")
    - export SHA_REMOTE_DC_COMPOSE=$(ssh $SSH_USER@$SSH_ADDRESS sha256sum $DEPLOY_PATH/defense_center/compose.yml || echo "NONE")
    - export SHA_REMOTE_DC_ENV=$(ssh $SSH_USER@$SSH_ADDRESS sha256sum $DEPLOY_PATH/defense_center/.env || echo "NONE")
  script:
    - |
        if [ "$SHA_REPO_SENSOR_COMPOSE" != "$SHA_REMOTE_SENSOR_COMPOSE" ]; then
          echo "Ada Perubahan docker-compose sensor..."
          ssh $SSH_USER@$SSH_ADDRESS "sudo docker-compose -f $DEPLOY_PATH/sensor_snort/compose.yml down || true"
          rsync -avz -e ssh $CI_PROJECT_DIR/.deploy/sensor_snort/compose.yml $SSH_USER@$SSH_ADDRESS:$DEPLOY_PATH/sensor_snort/compose.yml
        else
          echo "Tidak ada perubahan pada docker-compose sensor"
        fi

        if [ "$SHA_REPO_SENSOR_ENV" != "$SHA_REMOTE_SENSOR_ENV" ]; then
          echo "Ada Perubahan .env sensor..."
          rsync -avz -e ssh $CI_PROJECT_DIR/.deploy/sensor_snort/.env.example $SSH_USER@$SSH_ADDRESS:$DEPLOY_PATH/sensor_snort/.env
        else
          echo "Tidak ada perubahan pada .env sensor"
        fi

        if [ "$SHA_REPO_DC_COMPOSE" != "$SHA_REMOTE_DC_COMPOSE" ]; then
          echo "Ada Perubahan docker-compose defense center..."
          ssh $SSH_USER@$SSH_ADDRESS "sudo docker-compose -f $DEPLOY_PATH/defense_center/compose.yml down || true"
          rsync -avz -e ssh $CI_PROJECT_DIR/.deploy/defense_center/compose.yml $SSH_USER@$SSH_ADDRESS:$DEPLOY_PATH/defense_center/compose.yml
        else
          echo "Tidak ada perubahan pada docker-compose defense center"
        fi

        if [ "$SHA_REPO_DC_ENV" != "$SHA_REMOTE_DC_ENV" ]; then
          echo "Ada Perubahan .env defense center..."
          rsync -avz -e ssh $CI_PROJECT_DIR/.deploy/defense_center/.env.example $SSH_USER@$SSH_ADDRESS:$DEPLOY_PATH/defense_center/.env
        else
          echo "Tidak ada perubahan pada .env defense center"
        fi

        ssh $SSH_USER@$SSH_ADDRESS "cd $DEPLOY_PATH && sudo docker-compose -f defense_center/compose.yml pull && sudo docker-compose -f defense_center/compose.yml up -d --force-recreate"
        ssh $SSH_USER@$SSH_ADDRESS "cd $DEPLOY_PATH && sudo docker-compose -f sensor_snort/compose.yml pull && sudo docker-compose -f sensor_snort/compose.yml up -d --force-recreate"


