name: dast

services:
  grpc-dast:
    image: python:3.11-alpine
    depends_on:
      - sensor-api
    volumes:
      - $CI_PROJECT_DIR/.dast:/dast
    working_dir: /dast
    entrypoint: [""]
    command: >
      sh -c "
        python3 -m venv venv &&
        . venv/bin/activate &&
        pip install --no-cache-dir -r requirements.txt &&
        python3 grpc_dast.py
      "
    networks:
      - dast-network

  sensor-api:
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    command: "server -v"
    restart: unless-stopped
    depends_on:
      - broker
      - schema-registry
    ports:
      - "50051:50051"
    environment:
      - MES_SERVER_HOST=0.0.0.0
      - MES_SERVER_PORT=50051
      - MES_SERVER_INSECURE=true
      - MES_SERVER_MAX_MESSAGE_SIZE=1024
      - MES_SERVER_KAFKA_BROKERS=broker:29092
      - MES_SERVER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - MES_SERVER_KAFKA_GROUP_ID=sensor-api
      - MES_SERVER_KAFKA_TOPIC=sensor_events
    networks:
      - dast-network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512M

  broker:
    image: confluentinc/cp-kafka:7.8.0
    restart: unless-stopped
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_MESSAGE_MAX_BYTES=1073741824
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9101
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker:29093
      - KAFKA_LISTENERS=PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - dast-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=broker:29092
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    networks:
      - dast-network

networks:
  dast-network:
    driver: bridge